import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>ObbySoft</title>
				<meta name='ObbySoft Main page' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className=' bg-gradient-to-b from-black to-black top-0 absolute w-full' style={{ height: "800px" }}>
				<div>
					<h1 className='text-lg'>ObbySoft!</h1>
				</div>
			</div>
			<div className='bg-gray-500' style={{ height: "800px" }}>
				Hi
			</div>
		</>
	);
}
