import Head from "next/head";

export default function Home() {
	return (
		<div className='p-10 border border-gray-100 bg-gray-100 shadow-lg mx-auto m-10 w-3/5'>
			<Head>
				<title>ObbySoft</title>
				<meta name='ObbySoft Main page' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				<h1 className='text-lg'>ObbySoft! TESTING</h1>
			</div>
		</div>
	);
}
